### ISSUE TITLE
Allow many paths to be passed in

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/actions#38]
Users should be able to pass in multiple JSON files using the `plan-json` argument. This should be done using multiple lines. We should also support glob patterns here so that users can submit many plans that match a pattern:

```
- uses: overmindtech/actions/submit-plan@main
  id: submit-plan
  with:
    ovm-api-key: ${{ secrets.OVM_API_KEY }} # Generated within Overmind
    plan-json: | # locate multiple plan files to process at once
      ./tfplan.json
      ./plans/*.json
```
